version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "5010:5010"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - auth-service
      - tracking-service

  auth-service:
    build: ./auth-service
    env_file:
      - ./auth-service/.env
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
      - redis

  tracking-service:
    build: ./tracking-service
    env_file:
      - ./tracking-service/.env
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
      - redis

  ai-service:
    build: ./ai-service
    ports:
      - "8000:8000"

  realtime-service:
    build: ./realtime-service
    ports:
      - "5003:5003"

  notification-service:
    build: ./notification-service
    ports:
      - "5004:5004"


  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - neurotrack-mongo-data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  neurotrack-mongo-data:
